theme: jekyll-theme-modernist
permalink: /blog/:year/:month/:day/:title
repository: "mikegrundvig/mikegrundvig.github.io"
future: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      