theme: jekyll-theme-leap-day
permalink: /blog/:year/:month/:day/:title
repository: "mikegrundvig/mikegrundvig.github.io"
future: true
title: "Michael Grundvig"
description: "Yet another developer blog"
email_url: "mailto:michael@michaelgrundvig.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      